routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('', 'HomeController@index')->name('home');

    Route::resource('users', 'UserController');

    Route::post('visitor/{visitor_id}/check-out', 'VisitorController@checkOut')->name('visitor.checkout');
    Route::resource('visitor', 'VisitorController');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Route::redirect('/', env('APP_URL') . '/login');

app/Http/Controllers/Admin/VisitorController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use App\Http\Controllers\Controller;
use App\Models\Role;
use App\Models\User;
use App\Models\VisitorDetail;
use Carbon\Carbon;
use Symfony\Component\HttpFoundation\Response;
use Illuminate\Http\Request;
use Yajra\DataTables\Facades\DataTables;

class VisitorController extends Controller
{
    use AuthorizesRequests, ValidatesRequests;

    
    public function index(Request $request){
        abort_if(actionDenied('visitor_detail_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        if ($request->ajax()) {
            $query = VisitorDetail::all();
            $table = Datatables::of($query);

            $table->addColumn('actions', '&nbsp;');

            $table->editColumn('actions', function ($row) {
                $routePart = 'visitor';
                $viewGate = $routePart . '_show';
                $editGate = $routePart . '_edit';
                $deleteGate = $routePart . '_delete';

                return view('partials.admin.table_actions', compact(
                    'viewGate',
                    'editGate',
                    'deleteGate',
                    'routePart',
                    'row'
                ));
            });

            $table->editColumn('name', function ($row) {
                return $row->user->name ? $row->user->name : '';
            });
            $table->editColumn('phone', function ($row) {
                return $row->user->phone ? $row->user->phone : '';
            });
            $table->editColumn('is_walkin', function ($row) {
                return $row->is_walkin ? trans('global.yes') : trans('global.no');
            });
            $table->editColumn('vehicle_number', function ($row) {
                return $row->vehicle_number ? $row->vehicle_number : '';
            });
            $table->editColumn('check_in_at', function ($row) {
                return $row->check_in_at ? $row->check_in_at : '';
            });
            $table->editColumn('check_out_at', function ($row) {
                return $row->check_out_at ? $row->check_out_at : '';
            });
            $table->rawColumns(['actions']);

            return $table->make(true);
        }

        return view('admin.visitor.index');
    }

    public function create(){
        abort_if(actionDenied('visitor_detail_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.visitor.create');
    }

    public function store(Request $request){
        $request->validate([
            'name' => ['required'],
            'phone' => ['required', 'numeric', 'digits_between:10,15'],
            'purpose' => ['required'],
        ]);

        if(($request->is_walkin && $request->vehicle_number) || 
            (!$request->is_walkin && !$request->vehicle_number)
        ){
            return back()->withErrors([
                'is_walkin'      => trans('cruds.visitor.validation.is_walkin_verhicle_number_required'),
                'vehicle_number' => trans('cruds.visitor.validation.is_walkin_verhicle_number_required'),
            ]);
        }

        $user = User::create($request->all());
        $user->roles()->sync(Role::find(3));

        VisitorDetail::create([
            ...$request->all(),
            'check_in_at' => Carbon::now(),
            'user_id' => $user->id,
            'recorder_id' => auth()->user()->id,
        ]);

        return redirect()->route('admin.visitor.index');
    }

    public function show(Request $request, $id){
        abort_if(actionDenied('visitor_detail_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $object = VisitorDetail::find($id);

        return view('admin.visitor.show', compact('object'));
    }

    public function edit(Request $request, $id){
        abort_if(actionDenied('visitor_detail_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $object = VisitorDetail::find($id);

        return view('admin.visitor.edit', compact('object'));
    }

    public function update(Request $request, $id){
        $request->validate([
            'name' => ['required'],
            'phone' => ['required', 'numeric', 'digits_between:10,15'],
            'purpose' => ['required'],
        ]);

        if(($request->is_walkin && $request->vehicle_number) || 
            (!$request->is_walkin && !$request->vehicle_number)
        ){
            return back()->withErrors([
                'is_walkin'      => trans('cruds.visitor.validation.is_walkin_verhicle_number_required'),
                'vehicle_number' => trans('cruds.visitor.validation.is_walkin_verhicle_number_required'),
            ]);
        }

        $object = VisitorDetail::find($id);
        $object->update([
            ...$request->all(),
            'is_walkin' => $request->is_walkin ?? false
        ]);

        $object->user->update($request->all());

        return redirect()->route('admin.visitor.index');
    }

    public function checkout(Request $request, $id){
        $object = VisitorDetail::find($id);
        $object->update([
            'check_out_at' => Carbon::now(),
        ]);

        return redirect()->route('admin.visitor.index');
    }

    public function destroy(Request $request, $id){
        abort_if(actionDenied('visitor_detail_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $object = User::find($id);
        $object->delete();

        return back();
    }
}

resources/views/admin/visitor/create.blade.php
@extends('layouts.admin')

@section('body')
    <div class="card tw-rounded-2xl tw-shadow-md tw-border-white animation-float-in">
        <div class="card-header tw-text-base tw-font-bold border-radius-top">
            {{ trans('global.create') }} {{ trans('cruds.visitor.name') }}
        </div>
    
        <div class="card-body">
            <form method="POST" action="{{ route('admin.visitor.store') }}" enctype="multipart/form-data">
                @csrf
                <div class="form-group mb-4">
                    <label class="required" for="name">{{ trans('cruds.visitor.fields.name') }}</label>
                    <input class="form-control" type="text" name="name" id="name" required>
                    @if($errors->has('name'))
                        <div class="text-danger">
                            *{{ $errors->first('name') }}
                        </div>
                    @endif
                </div>
                <div class="form-group mb-4">
                    <label class="required" for="phone">{{ trans('cruds.visitor.fields.phone') }}</label>
                    <input class="form-control" type="text" name="phone" id="phone" required>
                    @if($errors->has('phone'))
                        <div class="text-danger">
                            *{{ $errors->first('phone') }}
                        </div>
                    @endif
                </div>
                <div class="form-group mb-4">
                    <label class="required" for="purpose">{{ trans('cruds.visitor.fields.purpose') }}</label>
                    <input class="form-control" type="text" name="purpose" id="purpose" required>
                    @if($errors->has('purpose'))
                        <div class="text-danger">
                            *{{ $errors->first('purpose') }}
                        </div>
                    @endif
                </div>
                <div class="form-group mb-4">
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="is_walkin" id="is_walkin" value="1">
                        <label class="form-check-label" for="approved">{{ trans('cruds.visitor.fields.is_walkin') }}</label>
                    </div>
                    @if($errors->has('is_walkin'))
                        <div class="text-danger">
                            *{{ $errors->first('is_walkin') }}
                        </div>
                    @endif
                </div>
                <div class="form-group mb-4">
                    <label class="required" for="vehicle_number">{{ trans('cruds.visitor.fields.vehicle_number') }}</label>
                    <input class="form-control" type="text" name="vehicle_number" id="vehicle_number">
                    @if($errors->has('vehicle_number'))
                        <div class="text-danger">
                            *{{ $errors->first('vehicle_number') }}
                        </div>
                    @endif
                </div>
                <div class="form-group mb-4">
                    <button class="btn btn-danger" type="submit">
                        {{ trans('global.submit') }}
                    </button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/visitor/edit.blade.php
@extends('layouts.admin')

@section('body')
    <div class="card tw-rounded-2xl tw-shadow-md tw-border-white animation-float-in">
        <div class="card-header tw-text-base tw-font-bold border-radius-top">
            {{ trans('global.update') }} {{ trans('cruds.visitor.name') }}
        </div>
    
        <div class="card-body">
            <form method="POST" action="{{ route('admin.visitor.update', $object->id) }}" enctype="multipart/form-data">
                @method('PUT')
                @csrf
                <div class="form-group mb-4">
                    <label class="required" for="name">{{ trans('cruds.visitor.fields.name') }}</label>
                    <input class="form-control" type="text" name="name" id="name" value="{{ $object->user->name }}" required>
                    @if($errors->has('name'))
                        <div class="text-danger">
                            *{{ $errors->first('name') }}
                        </div>
                    @endif
                </div>
                <div class="form-group mb-4">
                    <label class="required" for="phone">{{ trans('cruds.visitor.fields.phone') }}</label>
                    <input class="form-control" type="text" name="phone" id="phone" value="{{ $object->user->phone }}" required>
                    @if($errors->has('phone'))
                        <div class="text-danger">
                            *{{ $errors->first('phone') }}
                        </div>
                    @endif
                </div>
                <div class="form-group mb-4">
                    <label class="required" for="purpose">{{ trans('cruds.visitor.fields.purpose') }}</label>
                    <input class="form-control" type="text" name="purpose" id="purpose" value="{{ $object->purpose }}" required>
                    @if($errors->has('purpose'))
                        <div class="text-danger">
                            *{{ $errors->first('purpose') }}
                        </div>
                    @endif
                </div>
                <div class="form-group mb-4">
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="is_walkin" id="is_walkin" value="1" {{ $object->is_walkin == 1 ? 'checked' : '' }} >
                        <label class="form-check-label" for="approved">{{ trans('cruds.visitor.fields.is_walkin') }}</label>
                    </div>
                    @if($errors->has('is_walkin'))
                        <div class="text-danger">
                            *{{ $errors->first('is_walkin') }}
                        </div>
                    @endif
                </div>
                <div class="form-group mb-4">
                    <label class="required" for="vehicle_number">{{ trans('cruds.visitor.fields.vehicle_number') }}</label>
                    <input class="form-control" type="text" name="vehicle_number" id="vehicle_number" value="{{ $object->vehicle_number }}">
                    @if($errors->has('vehicle_number'))
                        <div class="text-danger">
                            *{{ $errors->first('vehicle_number') }}
                        </div>
                    @endif
                </div>
                <div class="form-group mb-4">
                    <button class="btn btn-danger" type="submit">
                        {{ trans('global.update') }}
                    </button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/visitor/index.blade.php
@extends('layouts.admin')

@section('body')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.visitor.create') }}">
                {{ trans('global.create') }} {{ trans('cruds.visitor.name') }}
            </a>
        </div>
    </div>

    <div class="card tw-rounded-2xl tw-shadow-md tw-border-white animation-float-in">
        <div class="card-header tw-text-lg tw-font-bold border-radius-top">
            {{ trans('cruds.visitor.title') }}
        </div>

        <div class="card-body">
            <table class=" table table-bordered table-striped table-hover ajaxTable datatable datatable-Visitor">
                <thead>
                    <tr>
                        <th>
                            {{ trans('cruds.visitor.fields.name') }}
                        </th>
                        <th>
                            {{ trans('cruds.visitor.fields.phone') }}
                        </th>
                        <th>
                            {{ trans('cruds.visitor.fields.is_walkin') }}
                        </th>
                        <th>
                            {{ trans('cruds.visitor.fields.vehicle_number') }}
                        </th>
                        <th>
                            {{ trans('cruds.visitor.fields.check_in_at') }}
                        </th>
                        <th>
                            {{ trans('cruds.visitor.fields.check_out_at') }}
                        </th>
                        <th>
                            {{ trans('global.action') }}
                        </th>
                    </tr>
                    <tr>
                        <td>
                            <input class="search" type="text" placeholder="{{ trans('global.search') }}">
                        </td>
                        <td>
                            <input class="search" type="text" placeholder="{{ trans('global.search') }}">
                        </td>
                        <td>
                            <input class="is_walkin_checkbox" type="checkbox" id="is_walkin_checkbox" value="1">
                        </td>
                        <td>
                            <input class="search" type="text" placeholder="{{ trans('global.search') }}">
                        </td>
                        <td>
                            <input class="search" type="text" placeholder="{{ trans('global.search') }}">
                        </td>
                        <td>
                            <input class="search" type="text" placeholder="{{ trans('global.search') }}">
                        </td>
                        <td>
                        </td>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
@endsection


@section('script')
@parent
<script>
    $(function () {
        let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)

        let dtOverrideGlobals = {
            buttons: dtButtons,
            info: false,
            processing: true,
            serverSide: true,
            retrieve: true,
            aaSorting: [],
            ajax: "{{ route('admin.visitor.index') }}",
            columns: [
                { data: 'name', name: 'name' },
                { data: 'phone', name: 'phone' },
                { data: 'is_walkin', name: 'is_walkin' },
                { data: 'vehicle_number', name: 'vehicle_number' },
                { data: 'check_in_at', name: 'check_in_at' },
                { data: 'check_out_at', name: 'check_out_at' },
                { data: 'actions', name: '{{ trans("global.actions") }}', "orderable": false }
            ],
            orderCellsTop: true,
            order: [[ 1, 'desc' ]],
            pageLength: 100,
        };
        let table = $('.datatable-Visitor').DataTable(dtOverrideGlobals);


        $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
            $($.fn.dataTable.tables(true)).DataTable()
                .columns.adjust();
        });
            
        let visibleColumnsIndexes = null;
        $('.datatable thead').on('input', '.search', function () {
            let strict = $(this).attr('strict') || false
            let value = strict && this.value ? "^" + this.value + "$" : this.value

            let index = $(this).parent().index()
            if (visibleColumnsIndexes !== null) {
                index = visibleColumnsIndexes[index]
            }

            table
                .column(index)
                .search(value, strict)
                .draw()
        });

        $(".is_walkin_checkbox").on("change", function(e) {
            let index = $(this).parent().index()
            table
                .column(index)
                .search($('#is_walkin_checkbox').is(':checked') ? "{{ trans('global.yes') }}" : "{{ trans('global.no') }}")
                .draw()
        });
    });

</script>
@endsection

resources/views/admin/visitor/show.blade.php
@extends('layouts.admin')

@section('body')
    <div class="card tw-rounded-2xl tw-shadow-md tw-border-white animation-float-in">
        <div class="card-header tw-text-base tw-font-bold border-radius-top">
            {{ trans('cruds.visitor.name') }}
        </div>
    
        <div class="card-body">
            <div class="form-group">
                <table class="table table-bordered table-striped">
                    <tbody>
                        <tr>
                            <th>
                                {{ trans('global.id') }}
                            </th>
                            <td>
                                {{ $object->id }}
                            </td>
                        </tr>
                        <tr>
                            <th>
                                {{ trans('cruds.visitor.fields.name') }}
                            </th>
                            <td>
                                {{ $object->user->name }}
                            </td>
                        </tr>
                        <tr>
                            <th>
                                {{ trans('cruds.visitor.fields.phone') }}
                            </th>
                            <td>
                                {{ $object->user->phone }}
                            </td>
                        </tr>
                        <tr>
                            <th>
                                {{ trans('cruds.visitor.fields.purpose') }}
                            </th>
                            <td>
                                {{ $object->purpose }}
                            </td>
                        </tr>
                        <tr>
                            <th>
                                {{ trans('cruds.visitor.fields.is_walkin') }}
                            </th>
                            <td>
                                {{ $object->is_walkin == 1 ? trans('global.yes') : trans('global.no') }}
                            </td>
                        </tr>
                        <tr>
                            <th>
                                {{ trans('cruds.visitor.fields.vehicle_number') }}
                            </th>
                            <td>
                                {{ $object->vehicle_number }}
                            </td>
                        </tr>
                        <tr>
                            <th>
                                {{ trans('cruds.visitor.fields.check_in_at') }}
                            </th>
                            <td>
                                {{ $object->check_in_at }}
                            </td>
                        </tr>
                        <tr>
                            <th>
                                {{ trans('cruds.visitor.fields.check_out_at') }}
                            </th>
                            <td>
                                {{ $object->check_out_at }}
                            </td>
                        </tr>
                        <tr>
                            <th>
                                {{ trans('cruds.visitor.fields.recorder') }}
                            </th>
                            <td>
                                {{ $object->recorder->name }}
                            </td>
                        </tr>
                    </tbody>
                </table>
                @if(!$object->check_out_at)
                <form class="d-inline" method="POST" action="{{ route('admin.visitor.checkout', $object->id) }}">
                    @csrf
                    <button class="btn btn-danger" type="submit">
                        {{ trans('cruds.visitor.fields.check_out') }}
                    </button>
                </form>
                @endif
                <div class="form-group">
                    <a class="btn btn-light mt-2" href="{{ route('admin.visitor.index') }}">
                        Back
                    </a>
                </div>
            </div>
        </div>
    </div>
@endsection