routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('', 'HomeController@index')->name('home');

    Route::resource('users', 'UserController');

    Route::post('visitor/{visitor_id}/check-out', 'VisitorController@checkOut')->name('visitor.checkout');
    Route::resource('visitor', 'VisitorController');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Route::redirect('/', env('APP_URL') . '/login');

app/Models/User.php
<?php

namespace App\Models;

use \DateTimeInterface;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasRoles;
    use SoftDeletes;
    use Notifiable;
    use HasFactory;
    use HasApiTokens;

    public $table = 'users';

    protected $hidden = [
        'remember_token',
        'password',
    ];

    protected $dates = [
        'email_verified_at',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'name',
        'phone',
        'email',
        'email_verified_at',
        'password',
        'remember_token',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    public function roles()
    {
        return $this->belongsToMany(Role::class);
    }

    public function hasRole($role_name)
    {
        foreach ($this->roles as $role){
            if ($role->role_name == $role_name)
                return true;
        }
        return false;
    }

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use App\Http\Controllers\Controller;
use App\Models\Role;
use App\Models\User;
use Symfony\Component\HttpFoundation\Response;
use Illuminate\Http\Request;
use Yajra\DataTables\Facades\DataTables;

class UserController extends Controller
{
    use AuthorizesRequests, ValidatesRequests;

    
    public function index(Request $request){
        abort_if(actionDenied('user_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        if ($request->ajax()) {
            $query = User::whereHas('roles', function ($roles) {
                return $roles->where('title', 'Staff');
            });
            $table = Datatables::of($query);

            $table->addColumn('actions', '&nbsp;');

            $table->editColumn('actions', function ($row) {
                $routePart = 'users';
                $viewGate = $routePart . '_show';
                $editGate = $routePart . '_edit';
                $deleteGate = $routePart . '_delete';

                return view('partials.admin.table_actions', compact(
                    'viewGate',
                    'editGate',
                    'deleteGate',
                    'routePart',
                    'row'
                ));
            });

            $table->editColumn('name', function ($row) {
                return $row->name ? $row->name : '';
            });
            $table->editColumn('email', function ($row) {
                return $row->email ? $row->email : '';
            });
            $table->rawColumns(['actions']);

            return $table->make(true);
        }

        return view('admin.user.index');
    }

    public function create(){
        abort_if(actionDenied('user_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.user.create');
    }

    public function store(Request $request){
        $request->validate([
            'name' => ['required'],
            'email' => ['required', 'email'],
            'password' => ['required'],
        ]);
        
        $user = User::create([
            ...$request->all(),
            'password' => bcrypt($request->password),
        ]);

        $user->roles()->sync(Role::find(2));

        return redirect()->route('admin.users.index');
    }

    public function show(Request $request, $id){
        abort_if(actionDenied('user_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $object = User::find($id);

        return view('admin.user.show', compact('object'));
    }

    public function edit(Request $request, $id){
        abort_if(actionDenied('user_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $object = User::find($id);

        return view('admin.user.edit', compact('object'));
    }

    public function update(Request $request, $id){
        $request->validate([
            'name' => ['required'],
            'email' => ['required', 'email'],
        ]);

        $object = User::find($id);
        $object->update($request->all());

        return redirect()->route('admin.users.index');
    }

    public function destroy(Request $request, $id){
        abort_if(actionDenied('user_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $object = User::find($id);
        $object->delete();

        return back();
    }
}

resources/views/admin/user/create.blade.php
@extends('layouts.admin')

@section('body')
    <div class="card tw-rounded-2xl tw-shadow-md tw-border-white animation-float-in">
        <div class="card-header tw-text-base tw-font-bold border-radius-top">
            {{ trans('global.create') }} {{ trans('cruds.user.name') }}
        </div>
    
        <div class="card-body">
            <form method="POST" action="{{ route('admin.users.store') }}" enctype="multipart/form-data">
                @csrf
                <div class="form-group mb-4">
                    <label class="required" for="name">{{ trans('cruds.user.fields.name') }}</label>
                    <input class="form-control" type="text" name="name" id="name" required>
                    @if($errors->has('name'))
                        <div class="text-danger">
                            *{{ $errors->first('name') }}
                        </div>
                    @endif
                </div>
                <div class="form-group mb-4">
                    <label class="required" for="email">{{ trans('cruds.user.fields.email') }}</label>
                    <input class="form-control" type="text" name="email" id="email" required>
                    @if($errors->has('email'))
                        <div class="text-danger">
                            *{{ $errors->first('email') }}
                        </div>
                    @endif
                </div>
                <div class="form-group mb-4">
                    <label class="required" for="password">{{ trans('cruds.user.fields.password') }}</label>
                    <input class="form-control" type="password" name="password" id="email" required>
                    @if($errors->has('password'))
                        <div class="text-danger">
                            *{{ $errors->first('password') }}
                        </div>
                    @endif
                </div>
                <div class="form-group mb-4">
                    <button class="btn btn-danger" type="submit">
                        {{ trans('global.submit') }}
                    </button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/user/edit.blade.php
@extends('layouts.admin')

@section('body')
    <div class="card tw-rounded-2xl tw-shadow-md tw-border-white animation-float-in">
        <div class="card-header tw-text-base tw-font-bold border-radius-top">
            {{ trans('global.update') }} {{ trans('cruds.user.name') }}
        </div>
    
        <div class="card-body">
            <form method="POST" action="{{ route('admin.users.update', $object->id) }}" enctype="multipart/form-data">
                @method('PUT')
                @csrf
                <div class="form-group mb-4">
                    <label class="required" for="name">{{ trans('cruds.user.fields.name') }}</label>
                    <input class="form-control" type="text" name="name" id="name" value="{{ $object->name }}" required>
                    @if($errors->has('name'))
                        <div class="text-danger">
                            *{{ $errors->first('name') }}
                        </div>
                    @endif
                </div>
                <div class="form-group mb-4">
                    <label class="required" for="email">{{ trans('cruds.user.fields.email') }}</label>
                    <input class="form-control" type="text" name="email" id="email" value="{{ $object->email }}" required>
                    @if($errors->has('email'))
                        <div class="text-danger">
                            *{{ $errors->first('email') }}
                        </div>
                    @endif
                </div>
                <div class="form-group mb-4">
                    <button class="btn btn-danger" type="submit">
                        {{ trans('global.update') }}
                    </button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.admin')

@section('body')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.users.create') }}">
                {{ trans('global.create') }} {{ trans('cruds.user.name') }}
            </a>
        </div>
    </div>

    <div class="card tw-rounded-2xl tw-shadow-md tw-border-white animation-float-in">
        <div class="card-header tw-text-lg tw-font-bold border-radius-top">
            {{ trans('cruds.user.title') }}
        </div>

        <div class="card-body">
            <table class=" table table-bordered table-striped table-hover ajaxTable datatable datatable-User">
                <thead>
                    <tr>
                        <th>
                            {{ trans('cruds.user.fields.name') }}
                        </th>
                        <th>
                            {{ trans('cruds.user.fields.email') }}
                        </th>
                        <th>
                            {{ trans('global.action') }}
                        </th>
                    </tr>
                    <tr>
                        <td>
                            <input class="search" type="text" placeholder="{{ trans('global.search') }}">
                        </td>
                        <td>
                            <input class="search" type="text" placeholder="{{ trans('global.search') }}">
                        </td>
                        <td>
                        </td>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
@endsection

@section('script')
@parent
<script>
    $(function () {
        let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
    
        let dtOverrideGlobals = {
            buttons: dtButtons,
            info: false,
            processing: true,
            serverSide: true,
            retrieve: true,
            aaSorting: [],
            ajax: "{{ route('admin.users.index') }}",
            columns: [
                { data: 'name', name: 'name' },
                { data: 'email', name: 'email' },
                { data: 'actions', name: '{{ trans("global.actions") }}', "orderable": false }
            ],
            orderCellsTop: true,
            order: [[ 1, 'desc' ]],
            pageLength: 100,
        };
        let table = $('.datatable-User').DataTable(dtOverrideGlobals);


        $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
            $($.fn.dataTable.tables(true)).DataTable()
                .columns.adjust();
        });
            
        let visibleColumnsIndexes = null;
        $('.datatable thead').on('input', '.search', function () {
            let strict = $(this).attr('strict') || false
            let value = strict && this.value ? "^" + this.value + "$" : this.value

            let index = $(this).parent().index()
            if (visibleColumnsIndexes !== null) {
                index = visibleColumnsIndexes[index]
            }

            table
                .column(index)
                .search(value, strict)
                .draw()
        });
    });

</script>
@endsection

resources/views/admin/user/show.blade.php
@extends('layouts.admin')

@section('body')
    <div class="card tw-rounded-2xl tw-shadow-md tw-border-white animation-float-in">
        <div class="card-header tw-text-base tw-font-bold border-radius-top">
            User Details
        </div>
    
        <div class="card-body">
            <div class="form-group">
                <table class="table table-bordered table-striped">
                    <tbody>
                        <tr>
                            <th>
                                ID
                            </th>
                            <td>
                                {{ $object->id }}
                            </td>
                        </tr>
                        <tr>
                            <th>
                                Name
                            </th>
                            <td>
                                {{ $object->name }}
                            </td>
                        </tr>
                        <tr>
                            <th>
                                Email
                            </th>
                            <td>
                                {{ $object->email }}
                            </td>
                        </tr>
                        <tr>
                            <th>
                                Create At
                            </th>
                            <td>
                                {{ $object->created_at }}
                            </td>
                        </tr>
                    </tbody>
                </table>
                <div class="form-group">
                    <a class="btn btn-light mt-2" href="{{ route('admin.users.index') }}">
                        Back
                    </a>
                </div>
            </div>
        </div>
    </div>
@endsection